# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!
project 'sleepcoacher'

target 'sleepcoacher' do
	pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.0.0'
	pod 'SwiftyJSON', '3.0.0'
	pod 'ResearchKit', '~> 1.0'
	pod 'SQLite.swift', '~> 0.11.5'
end


target 'sleepcoacherTests' do
	pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.0.0'
	pod 'SwiftyJSON', '3.0.0'
	pod 'ResearchKit', '~> 1.0'
end

target 'sleepcoacherUITests' do
	pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.0.0'
	pod 'SwiftyJSON', '3.0.0'
	pod 'ResearchKit', '~> 1.0'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
